# -*- coding: utf-8 -*-
"""visualizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RF7RBeYRajZ9NqB1Aiy2yVZWB4wyQ1u1
"""

! rm -rf  swiggy_order_visualizer
! git clone https://github.com/snehabarshamishra/swiggy_order_visualizer

!ls
!pwd

import json
f = open("/content/swiggy_order_visualizer/sample_data.json", "r")
order_history = f.read()
order_history_json = json.loads(order_history)

df_order_history = json_normalize(order_history_json, max_level=100)

order_item = json_normalize(order_history_json, 'order_items', ['order_id'])

df_order_item = order_item[['item_id', 'name', 'order_id', 'total', 'category_details.category', 'category_details.sub_category', 'quantity']]

# Column vs row list
df_order_history.shape

filtered_df = df_order_history[['order_id', 'restaurant_name', 'order_time', 'order_delivery_status', 'order_total']]

import pandas as pd
final_df = pd.merge(filtered_df, df_order_item, on='order_id')

import datetime as dt
final_df['order_timestamp'] = pd.to_datetime(final_df['order_time'])
# :%H:%M:%S.%f

final_df['order_date'] = final_df['order_timestamp'].dt.date

final_df['order_time1'] = final_df['order_timestamp'].dt.time

filtered_df['order_timestamp'] = pd.to_datetime(filtered_df['order_time'])
filtered_df['order_date'] = filtered_df['order_timestamp'].dt.date
filtered_df['order_time1'] = filtered_df['order_timestamp'].dt.time

filtered_df.head(1)

filtered_df['order_total'].sum()

filtered_df.head(4)

filtered_df[((filtered_df['order_timestamp']>pd.Timestamp(2020,3,23)) & (filtered_df['order_timestamp']<pd.Timestamp(2020,4,2)))]['order_total'].sum()
